version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - APP_ENV=production
    networks:
      my_net:
        ipv4_address: 192.168.50.2  # IP estática para el contenedor

networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24  # ✅ Subnet correcta