version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      custom_network:
        ipv4_address: 192.168.50.100  # 🔹 IP Fija para el contenedor

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24  # 🔹 Rango de IPs disponibles
